#!/usr/bin/env bash
# Displays the contents of the current directory in list format.
#   Only displays the part of the name after the first dash. 

for f in *; do
    echo "$f" | cut -d '-' -f 2

done
